# Generated by Django 5.0.4 on 2024-04-24 04:54

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, help_text='Contact phone number', max_length=31)),
                ('balanc', models.IntegerField(default=0)),
                ('telegram_id', models.CharField(default='', max_length=10000, verbose_name='Id Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'ordering': ['user'],
            },
        ),
    ]
