# Generated by Django 5.0.4 on 2024-04-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupdate',
            name='balanc',
        ),
        migrations.RemoveField(
            model_name='userupdate',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='userupdate',
            name='type_of_account',
            field=models.CharField(choices=[('seller', 'seller'), ('worker', 'worker')], default=('worker', 'worker')),
        ),
    ]
