# Generated by Django 5.0.4 on 2024-04-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userupdate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdate',
            name='type_of_account',
            field=models.CharField(choices=[('seller', 'Продавец'), ('worker', 'Покупатель')], default=('worker', 'Покупатель')),
        ),
    ]
