# Generated by Django 5.0.4 on 2024-04-24 09:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userupdate_type_of_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdate',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=12, region=None, verbose_name='Contact phone number'),
        ),
    ]
